### ISSUE TITLE
Enemies damage player if they reach goal location

### ISSUE THREAD

**Issue by LanceBailey** [GamesByMoonlight/january#16]
Requires #14, #7

When the enemies reach the target position, they should call a method that causes them to damage player and update the player's health in the GameManager.

**Comment by LanceBailey** [comment]
Right now enemies just float towards the player.

It may make more sense to just make a zone that causes the enemies to hurt the player if they enter it for now, until the nav mesh stuff is implemented (feature #37).

**Comment by ciscom1971** [comment]
ok uploaded brange 16  added player damage to gamemanager and added gameobject playerTarget so enemy can target player and the player target script
