### ISSUE TITLE
Enemy movement logic

### ISSUE THREAD

**Issue by LanceBailey** [GamesByMoonlight/january#37]
Establish a Navmesh for enemy movement

Put a goal point on the Nav Mesh

Improve Enemy logic to follow nav mesh to move towards goal point

**Comment by ciscom1971** [comment]
I added a navMesh and a target goal point for enemy in front of table.. I need to remove the mesh render so it will be invisible to player.

**Comment by ciscom1971** [comment]
I completed this in branch 16
