### ISSUE TITLE
Create a waypoint system for the NavMesh Agent system

### ISSUE THREAD

**Issue by LanceBailey** [GamesByMoonlight/january#60]
Establish a series of waypoints through the room that start about 2/3 of the way up the room, then about 1/3, then finally around the table.  These will be referenced by the NavMesh agents to cause the enemies to approach the player.

**Comment by LanceBailey** [comment]
In my head the most reasonable way to make this would be to have them as children to a parent gameobject, or all referenced by a master waypoint manager, so that a random waypoint can easily be picked from each "tier".

**Comment by ciscom1971** [comment]
after doing it this way I all of a sudden thought of a much better way to do this..i may change it at a latter time

**Comment by ciscom1971** [comment]
Forced the game object order in the array(List) of waypoints to alway move closer to objects

**Comment by LanceBailey** [comment]
pr #69
